name: Run TTS Example

on: [push]

jobs:
  tts-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install speechbrain torchaudio

    - name: Create TTS script
      run: |
        echo "import torchaudio" > run_tts.py
        echo "from speechbrain.inference.TTS import Tacotron2" >> run_tts.py
        echo "from speechbrain.inference.vocoders import HIFIGAN" >> run_tts.py
        echo "" >> run_tts.py
        echo "# Initialize TTS (tacotron2) and Vocoder (HiFIGAN)" >> run_tts.py
        echo "tacotron2 = Tacotron2.from_hparams(source='speechbrain/tts-tacotron2-ljspeech', savedir='tmpdir_tts')" >> run_tts.py
        echo "hifi_gan = HIFIGAN.from_hparams(source='speechbrain/tts-hifigan-ljspeech', savedir='tmpdir_vocoder')" >> run_tts.py
        echo "" >> run_tts.py
        echo "# Running the TTS" >> run_tts.py
        echo "mel_output, mel_length, alignment = tacotron2.encode_text('Mary had a little lamb')" >> run_tts.py
        echo "" >> run_tts.py
        echo "# Running Vocoder (spectrogram-to-waveform)" >> run_tts.py
        echo "waveforms = hifi_gan.decode_batch(mel_output)" >> run_tts.py
        echo "" >> run_tts.py
        echo "# Save the waveform" >> run_tts.py
        echo "torchaudio.save('example_TTS.wav', waveforms.squeeze(1), 22050)" >> run_tts.py

    - name: Run TTS script
      run: python run_tts.py

    - name: Upload TTS output
      uses: actions/upload-artifact@v2
      with:
        name: example_TTS
        path: example_TTS.wav
